### ISSUE TITLE
Returning a Stream

### ISSUE THREAD

**Issue by pentlander** [alexcrichton/futures-await#7]
It looks like the current async/await only uses yield without a value, however I saw that in the RFC it mentioned the ability to yield a value. It seems like yielding a value could be used to implement a Steam, is this possible in the new nightly? Ideally it would look something like this (ignoring some slight syntax errors):

```rust
// It would convert the iterator to Stream<Baz>
#[async] 
fn foo(stream: Stream<Bar>) -> impl Iterator<Result<Baz>> {
    #[async]
    for bar in stream {
        let baz = bar_to_baz(bar);
        yield baz;
    } 
} 
```

**Comment by rozaliev** [comment]
It is possible with current nightly to convert a generator into an iterator. Like this: https://play.rust-lang.org/?gist=8b638dcfceeea253e8a82768deea110a&version=nightly

But I'm not sure if it will work for Stream -> Iterator using [async] for loop. @alexcrichton might help here.

**Comment by alexcrichton** [comment]
Thanks for the report! This deifnitely isn't implemented yet and I'm not 100% sure what the best syntax is for doing this, so I'd be up for suggestions!

**Comment by pentlander** [comment]
It should also be able to handle early yields in a loop like this:
```
#[async]
fn foo(vec: Vec<u32>) -> Generator<Result<u32>> {
    for i in vec {
        if i % 2 == 0 {
            // This is a macro that will yield a value and continue. Not sure if you need a 
            // separate macro for this. Maybe you could use ? somehow
            yield_loop!(Result::ok(i))
        }
        yield Result::ok(i * 3)
    }
}
```

I'll try to think of a syntax that would make sense for this.

**Comment by Nemo157** [comment]
I just pushed a super quick hacky implementation of this to make sure it works, it successfully runs the echo example with an async generated stream: https://github.com/Nemo157/futures-await/tree/stream

I have a crate that I'm going to try to convert over to using this and then see if there are other ways the syntax could be changed to make it look nicer.

**Comment by alexcrichton** [comment]
Nice!

I'm personally not sure what we want this to look like syntactically, though. It looks like currently you've got:

```rust
#[async_stream]
fn handle_client(socket: TcpStream) -> io::Result<u64> {
    // ...
        yeld!(length);
    // ...

    Ok(())
}
```

Which is interesting! It looks like the `io::Result` bit is defining the error type of the stream, and the `<u64>` is defining the `Item` type of the stream? I like the idea of using a dedicated macro for "I've just produced an item on the stream"!

**Comment by Nemo157** [comment]
Yep, this was basically the minimal amount of change to the `async` macro to make it possible to generate a `Stream` instead of `Future` while keeping compatibility with the `await!` macro.

The type flow is pretty interesting, the macro takes a function with a `T: Try` return value, splits the success and error cases across the different generator paths into a `Generator<Yield=Async<T::Ok>, Return=Result<(), T::Error>>`, which the shim then pulls back together into a `Stream<Item=T::Ok, Error=T::Error>`. It doesn't actually use values of type `T` anywhere though, all errors would have to be returned via `?` if `T != Result`.

That last point is a change since when I first posted this, I really disliked the `Ok(())` at the end when the function said it returned `Result<u64>` so moved that into the macro which forces the generator return type to be `Result<(), T::Error>`. I still would prefer having a signature like 

```rust
#[async_stream]
fn handle_client(socket: TcpStream) -> Stream<Item=u64, Error=io::Error> {
```

but it doesn't seem like that is possible without having the macro just doing textual parsing of the return value. (Similarly I would prefer normal `#[async]` functions to actually say they're returning `Future`, but that is less bad since a `Result` maps a lot more easily to a `Future` than to a `Stream`).

**Comment by alexcrichton** [comment]
Hm so one thing I've tried to strive for as much as possible is that if a function has `-> T` then `return t: T` works anywhere in the function (which makes it difficult here)

I wonder, though, maybe...

```rust
#[async_stream(item = T)]
fn foo() -> Result<(), E>{ // must be `()`!
    // ...
    stream_yield!(item: T);
}
```

would generate a `impl Stream<Item = T, Error = E>` perhaps?

**Comment by Nemo157** [comment]
Yep, that would work as well (although it looks like `syn` is a bit lacking in attribute parsing still). I'll try and update my branch to that tomorrow (and probably open a separate issue to discuss the return types).

**Comment by alexcrichton** [comment]
Ok, thanks!

**Comment by rushmorem** [comment]
@alexcrichton @Nemo157 How about:-

```rust
#[async_stream]
fn foo() -> Result<Option<T>, E> {
    // ...
        stream_yield!(T);
    // ...
    Ok(None)
}
```

to generate a impl Stream<Item = T, Error = E> instead? This is consistent with `Poll` and is more intuitive IMHO.

**Comment by spinda** [comment]
My feeling of this is that the return type describes the way that the 
function terminates. A Future terminates with either a value or an 
error, translating to `Result<T, E>`. A Stream terminates with either 
nothing or an error, translating to `Result<(), E>`. Yielding items is 
something the Stream does before termination, hence the item type does 
not figure into its return type.

**Comment by spinda** [comment]
Also, has yielding multiple items (i.e. an iterator or collection of 
items) from a single yield statement been considered? Could that allow 
for more performant code?

**Comment by rushmorem** [comment]
This makes sense. However, you could also argue that terminating with `None` is the same as terminating with nothing. Using an `Option` for such functions is what both the `std` library (`Iterator`) and the `futures` crate (`Poll`) have been doing so far. I don't see any reason to deviate in this case.

**Comment by Nemo157** [comment]
@rushmorem what do you think the behaviour of 

```
#[async_stream]
fn foo() -> Result<Option<T>, E> {
    // ...
        stream_yield!(T);
    // ...
    Ok(Some(T))
}
```

should be?

It would be possible to block this by making the generator `Generator<Yield=Async<T>, Return=Result<Option<!>, E>>`, but then we're back to the macro-ed return type not directly matching the declared return type.

**Comment by rushmorem** [comment]
@Nemo157 This is clearly a bug. The assumption with `Iterator` and `Stream` is that if we receive `Some(T)` we will receive more results. Again, I don't see any reason to think otherwise here.

Having said that, I think generators actually give us a unique opportunity to handle this elegantly. Since calling `generator.resume()` after completion [will panic](https://play.rust-lang.org/?gist=b22e2b6ab451d4e68e0632ab206a8381&version=nightly) with "generator resumed after completion", can't we catch that and treat it like we got `Ok(None)` instead?

**Comment by Nemo157** [comment]
Updated and rebased [my branch](https://github.com/Nemo157/futures-await/tree/stream), now it matches @alexcrichton's last syntax and uses all the latest changes from master.

Unfortunately most of my `Stream` implementations also need a `Sink` implementation so I can't use this easily (maybe it's possible via `Stream::split`, separately modifying them then joining them back together, but I haven't looked into that yet).

---

@rushmorem I'm against providing users of a library the ability to write what looks like correct code, but is guaranteed to panic at runtime; we have a really good type system so we should use it to avoid writing incorrect code in the first place.

The main problem with using `Result<Option<T>, E>` as the return type is now you have 5 ways to pass a value from the function to the `Stream` shim, which then needs to map them into the 4 return values of `Stream::poll`:

```rust
{
  yield Async::NotReady, // from inside `await!`
  yield Async::Ready(T), // from inside `stream_yield!`
  return Ok(Some(T)),    // from the function
  return Ok(None),       // from the function
  return Err(E),         // from the function
}
=>
{
  Ok(Async::NotReady), 
  Ok(Async::Ready(Some(T))),
  Ok(Async::Ready(None)),
  Err(E)
}
```

The current implementation avoids this by having only one `Ok` case: `Ok(())`, so you get a nice direct map between the generator return values and the `Stream::poll` return values:

```rust
yield Async::NotReady   =>   Ok(Async::NotReady),
yield Async::Ready(T)   =>   Ok(Async::Ready(Some(T))),
return Ok(())           =>   Ok(Async::Ready(None)),
return Err(E)           =>   Err(E),
```

**Comment by rushmorem** [comment]
@Nemo157 The problem I have with @alexcrichton's last syntax is that it removes the type from the function signature into the attribute macro. Someone could write something like this:-

```rust
#[async_stream(item = T)]
// Some
// very
// long
// documentation
// or comments
fn foo() -> Result<(), E> {
  // ..
}
```

You will have to scroll through that documentation just to see the return type. Now just the function signature doesn't tell you what the function returns.

> I'm against providing users of a library the ability to write what looks like correct code, but is guaranteed to panic at runtime; we have a really good type system so we should use it to avoid writing incorrect code in the first place.

I totally agree with you here. However, my suggestion above doesn't result in code that panics at all. I did say:-

> I think generators actually give us a unique opportunity to handle this elegantly. Since calling generator.resume() after completion will panic with "generator resumed after completion", can't we catch that and treat it like we got Ok(None) instead?

However I had also said that "This is clearly a bug" but we if we handled it like I suggested we should, it will actually become correct code. It won't panic because we will be handling the panic from `.resume()` (resume won't even panic, see my edit at the end).

> The main problem with using Result<Option<T>, E> as the return type is now you have 5 ways to pass a value from the function to the Stream shim, which then needs to map them into the 4 return values of Stream::poll

Not really. The mapping with this approach is even more direct than what you are currently doing

```rust
yield Async::NotReady    =>   Ok(Async::NotReady),
yield Async::Ready(T)    =>   Ok(Async::Ready(Some(T))),
return Ok(Option<T>)     =>   Ok(Async::Ready(Option<T>)),
return Err(E)            =>   Err(E),
```

EDIT: After looking at your code, I can see that we don't even have to resort to catching panics. You simply need to add another `bool` field in `GenFuture` to mark it done. In `GeneratorState::Complete` process it as normal and mark the boolean as done. Then in your `poll` before calling `resume()` you simply add this check:-

```rust
if self.done {
    return Ok(Async::Ready(None));
}
```

**Comment by Nemo157** [comment]
> Now just the function signature doesn't tell you what the function returns.

I do agree with that, but my preferred solution is #15 so that the signature does specify exactly what the function returns.

> The mapping with this approach is even more direct than what you are currently doing

I shouldn't have said direct map, what I actually meant was a bijection between the return states. If you expand the `Option<T>` types in your map:

```rust
yield Async::NotReady    =>   Ok(Async::NotReady),
yield Async::Ready(T)    =>   Ok(Async::Ready(Some(T))),
return Ok(Some(T))       =>   Ok(Async::Ready(Some(T))),
return Ok(None)          =>   Ok(Async::Ready(None)),
return Err(E)            =>   Err(E),
```

you have 2 different return states from the function that result in the same return from `poll`, which leads to two different ways of writing the same stream:

```rust
#[async_stream]
fn foo() -> Result<Option<i32>, !> {
    stream_yield!(1);
    stream_yield!(2);
    stream_yield!(3);
    Ok(None)
}

#[async_stream]
fn foo() -> Result<Option<i32>, !> {
    stream_yield!(1);
    stream_yield!(2);
    Ok(Some(3))
}
```

IMO this is a downside since I dislike having to decide between which style to use for relatively trivial things like this (and hate having to switch if the implementation changes and there's now a slight preference for the other style).

I think at this point I'm pretty much so-so about the two syntaxes, they both have their upsides and downsides, so having some other people weigh in on them would be great.

**Comment by Nemo157** [comment]
> Also, has yielding multiple items (i.e. an iterator or collection of items) from a single yield statement been considered? Could that allow for more performant code?

@spinda I don't believe that would improve performance significantly. It would require the `Generator` to `Stream` shim to store the last collection returned, then each time it's polled check if the collection it currently has is exhausted and either return its next value or poll the `Generator` to see if it has a new collection to return values from.

Currently you can just iterate the collection in the `Generator` and yield each element individually; then the generated code would do basically the same thing I described above inside the `Generator`, but only during that segment of the code flow so that other parts will not have the extra cost of checking the collection

```rust
fn foo() -> impl Future<Item=u32, Error=!> { ... }

#[async_stream(item = u32)]
fn bar() -> Result<!, !> {
    loop {
        let i = await!(foo());
        for j = 0..i {
            stream_yield!(j);
        }
    }
}
```

(Hmm, I don't think `Result<!, !>` works currently for a never-ending, never-failing `Stream`, but it should).

**Comment by spinda** [comment]
@Nemo157 I see. My thinking was along the lines of resuming the generator and then yielding from it for each collection item being more expensive than having the `Stream::poll` method directly retrieving the next item without jumping into the generator. But I'm not really familiar with the performance characteristics of Rust's generators implementation.

**Comment by rushmorem** [comment]
> I do agree with that, but my preferred solution is https://github.com/alexcrichton/futures-await/issues/7 so that the signature does specify exactly what the function returns.

@Nemo157 I have some reservations about the approach in that issue but let's put that aside for now.

> IMO this is a downside since I dislike having to decide between which style to use for relatively trivial things like this (and hate having to switch if the implementation changes and there's now a slight preference for the other style).

I really don't understand your argument here. This is true for any function which returns an `Option`, `async` or not. If you don't like it that much you could also just do

```rust
#[async_stream]
fn foo() -> Result<i32> {
    stream_yield!(1);
    stream_yield!(2);
    Ok(3)
}
```

which has an advantage of looking the same as an `async` macro. IMHO, we should still use an `Option` for these 2 reasons:-

-  A function signature like `fn foo() -> Result<Option<i32>>` is consistent with how streams of data are represented in Rust (the `std` library's `Iterator` and `futures`'s `Poll`). I know I have said this multiple times before but I can't stress enough how important this is. Consistent APIs are very important in libraries.
- An `Option` makes it easier to write cleaner code in certain cases. For example consider the following example

```rust
#[async_stream]
fn foo() -> Result<Option<i32>> {
    #[async]
    // assume items was produced by some stream we have no way of knowing when it ends
    for item in items {
        stream_yield!(item);
    }
   // If we weren't using an option but returning an `i32` directly it would suddenly become
   // frustrating to write this seemingly trivial function. What would we return here?
    Ok(None)
}
```

As for

```rust
#[async_stream]
fn foo() -> Result<Option<i32>> {
    stream_yield!(1);
    stream_yield!(2);
    stream_yield!(3);
    Ok(None)
}

#[async_stream]
fn foo() -> Result<Option<i32>> {
    stream_yield!(1);
    stream_yield!(2);
    Ok(Some(3))
}
```

while both approaches are interchangeable, we only have to document the first approach but if someone uses the second approach, who cares... It will still work. Neither of approach is wrong. The only advantage of the first one is that it will result in one less function call. There are actually cases where the second approach would be more favourable. Say you want to use a `Stream` because those that's how the API should work in future but for now you only have one item you want to return. Instead of

```rust
#[async_stream]
fn foo() -> Result<Option<i32>> {
    stream_yield!(1);
    Ok(None)
}
```

I would rather just write

```rust
#[async_stream]
fn foo() -> Result<Option<i32>> {
    Ok(Some(1))
}
```

**Comment by Nemo157** [comment]
> A function signature like `fn foo() -> Result<Option<i32>>` is consistent with how streams of data are represented in Rust (the `std` library's `Iterator` and `futures`'s `Poll`)

This is definitely true for non-generator based implementations; but I don't believe it applies to generator based implementations because the generator itself provides the division between producing an item via `yield` and completing the data stream via `return`. For another example of this look at [the generator based `Iterator` implementation](https://play.rust-lang.org/?gist=8b638dcfceeea253e8a82768deea110a&version=nightly) that [@rozaliev linked earlier](https://github.com/alexcrichton/futures-await/issues/7#issuecomment-325864795); this uses a `Generator<Yield = T>` to produce an `Iterator<Item = T>` (and ignores the return value, but uses `Return = ()` in the example generator).

The difference between the `Iterator` and `Stream` versions are then simply:

 * The `Stream` might not be ready to produce an item:
   * Change the `Yield` type from `T` to `Async<T>` to allow returning `NotReady`
 * The `Stream` might fail:
   * Change the `Result` type from `()` to `Result<(), E>` to allow returning an error

**Comment by rushmorem** [comment]
I understand this. My argument is that there is no reason to change the API just because when can when what we are ending up with isn't significantly better than what we already have. Being generator based is an implementation detail.

**Comment by manuels** [comment]
Any news on this issue? Being able to return a `Stream` would be a really great feature!

**Comment by Nemo157** [comment]
I can open a PR for [my branch](https://github.com/Nemo157/futures-await/tree/stream) if people are happy with the API (see https://github.com/alexcrichton/futures-await/issues/7#issuecomment-326794129). Personally I'm not happy with defining the item type in the attribute so have been using [my other branch](https://github.com/Nemo157/futures-await/tree/alternate-signatures) that includes both this and #15 in one ([for example](https://github.com/Nemo157/mplex-rs/blob/dbafa822e633208d69a9302abd461bd5a073a7c1/src/stream.rs#L126-L140)).

It needs another rebase, some de-duplication and some tests added, but I'm happy to do that if there's some consensus on the API.

**Comment by alexcrichton** [comment]
@Nemo157 a PR to help take a look and review the API would be great!

**Comment by manuels** [comment]
Thanks for the great work, @Nemo157!

I think it's a bit wired to return a `Result<(),E>` although some stream/iterator/generator is expected to be returned.
Any reason why not to return a `impl Stream<Item=i32, Error=E>`?

**Comment by Nemo157** [comment]
@manuels [That is my preference as well](https://github.com/alexcrichton/futures-await/issues/15), especially because it allows unifying all of `impl Future`/`impl Stream`/`Box<Future>`/`Box<Stream>` under one `#[async]` macro. The current PR is following the [existing design](https://github.com/alexcrichton/futures-await/issues/7#issuecomment-326666735) of writing the return type from the perspective of the function body.
